In [ ]:
!nvidia-smi

Tue Jan 19 04:45:16 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.27.04    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8    10W /  70W |      0MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
from __future__ import absolute_import, division, print_function, unicode_literals

try:
  !pip uninstall tb-nightly tensorboardX tensorboardX
  !pip install tf-nightly
except Exception:
  pass
import tensorflow as tf

import os
import datetime
import tensorflow_datasets as tfds

%load_ext tensorboard



Uninstalling tb-nightly-2.5.0a20210118:
  Would remove:
    /usr/local/bin/tensorboard
    /usr/local/lib/python3.6/dist-packages/tb_nightly-2.5.0a20210118.dist-info/*
    /usr/local/lib/python3.6/dist-packages/tensorboard/*
  Would not remove (might be manually added):
    /usr/local/lib/python3.6/dist-packages/tensorboard/util/argparse_util.py
Proceed (y/n)? y
  Successfully uninstalled tb-nightly-2.5.0a20210118
  Using cached https://files.pythonhosted.org/packages/26/d1/b1c621ccf98bb2f95f7d85037be40c154d73fe0819d257f07a446a1f01da/tb_nightly-2.5.0a20210118-py3-none-any.whl


In [ ]:
import pkg_resources

for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins'):
  print(entry_point.dist)


tensorboard 2.4.0
tensorboard-plugin-wit 1.7.0
tb-nightly 2.5.0a20210118


In [ ]:
!rm -r /usr/local/lib/python3.8/dist-packages/tensorboardcolab-0.0.22.dist-info/

rm: cannot remove '/usr/local/lib/python3.8/dist-packages/tensorboardcolab-0.0.22.dist-info/': No such file or directory


In [ ]:
print(tf.__version__)

2.5.0-dev20210114


In [ ]:
tf.config.experimental.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
datasets, info = tfds.load('amazon_us_reviews/Mobile_Electronics_v1_00', with_info=True)
train_datasets = datasets['train']

In [ ]:
info

tfds.core.DatasetInfo(
    name='amazon_us_reviews',
    version=0.1.0,
    description='Amazon Customer Reviews (a.k.a. Product Reviews) is one of Amazons iconic products. In a period of over two decades since the first review in 1995, millions of Amazon customers have contributed over a hundred million reviews to express opinions and describe their experiences regarding products on the Amazon.com website. This makes Amazon Customer Reviews a rich source of information for academic researchers in the fields of Natural Language Processing (NLP), Information Retrieval (IR), and Machine Learning (ML), amongst others. Accordingly, we are releasing this data to further research in multiple disciplines related to understanding customer product experiences. Specifically, this dataset was constructed to represent a sample of customer evaluations and opinions, variation in the perception of a product across geographical regions, and promotional intent or bias in reviews.

Over 130+ million cus

In [ ]:
print(train_datasets)

<PrefetchDataset shapes: {data: {customer_id: (), helpful_votes: (), marketplace: (), product_category: (), product_id: (), product_parent: (), product_title: (), review_body: (), review_date: (), review_headline: (), review_id: (), star_rating: (), total_votes: (), verified_purchase: (), vine: ()}}, types: {data: {customer_id: tf.string, helpful_votes: tf.int32, marketplace: tf.string, product_category: tf.string, product_id: tf.string, product_parent: tf.string, product_title: tf.string, review_body: tf.string, review_date: tf.string, review_headline: tf.string, review_id: tf.string, star_rating: tf.int32, total_votes: tf.int32, verified_purchase: tf.int64, vine: tf.int64}}>


In [ ]:
len(list(train_datasets))

104975

In [ ]:
BUFFER_SIZE = 30000
BATCH_SIZE = 128

In [ ]:
train_datasets = train_datasets.shuffle(BUFFER_SIZE, reshuffle_each_iteration=False)

In [ ]:
for reviews in train_datasets.take(2):
  print(reviews)

{'data': {'customer_id': <tf.Tensor: shape=(), dtype=string, numpy=b'42073732'>, 'helpful_votes': <tf.Tensor: shape=(), dtype=int32, numpy=0>, 'marketplace': <tf.Tensor: shape=(), dtype=string, numpy=b'US'>, 'product_category': <tf.Tensor: shape=(), dtype=string, numpy=b'Mobile_Electronics'>, 'product_id': <tf.Tensor: shape=(), dtype=string, numpy=b'B000CDGW8Y'>, 'product_parent': <tf.Tensor: shape=(), dtype=string, numpy=b'434298526'>, 'product_title': <tf.Tensor: shape=(), dtype=string, numpy=b'MP3 Player'>, 'review_body': <tf.Tensor: shape=(), dtype=string, numpy=b'I had this product before , but it mistakenly fell and cracked into pieces right before my eyes.  If you have good quality batteries you are good for a long period of time.  The replacement I purchased after my previous item fell into pieces was not in good shape as compared to my previous item, but the shipping came right on time. thanks.'>, 'review_date': <tf.Tensor: shape=(), dtype=string, numpy=b'2013-02-22'>, 'review

In [ ]:
for reviews in train_datasets.take(10):
  review_text  = reviews['data']
  print(review_text.get('review_body').numpy())
  print(review_text.get('star_rating'))
  print(tf.where(review_text.get('star_rating')>3 , 1 ,0).numpy())


b'I had this product before , but it mistakenly fell and cracked into pieces right before my eyes.  If you have good quality batteries you are good for a long period of time.  The replacement I purchased after my previous item fell into pieces was not in good shape as compared to my previous item, but the shipping came right on time. thanks.'
tf.Tensor(4, shape=(), dtype=int32)
1
b'It works great. Little loose in latch but works great for dog owners.'
tf.Tensor(5, shape=(), dtype=int32)
1
b'Fit perfect, and rather than throw your old GPS away, fix it instead. Shipping was quick, even for China.'
tf.Tensor(5, shape=(), dtype=int32)
1
b'More than once by now the item just went off, while in use and having more than 50 % of charge. In this occasion it needs to be restarted, holding the power button for 20-30 ns.'
tf.Tensor(3, shape=(), dtype=int32)
0
b'It was just what I needed, wanted and more.  I could not bet happier.  I would highly recommend this product.'
tf.Tensor(5, shape=(), dtyp

In [ ]:
tokenizer = tfds.deprecated.text.Tokenizer()

vocabulary_set = set()
for __, reviews in train_datasets.enumerate() :
  #print(reviews)
  review_text = reviews['data']
  reviews_tokens = tokenizer.tokenize(review_text.get('review_body').numpy())
  vocabulary_set.update(reviews_tokens)

vocab_size = len(vocabulary_set)
vocab_size



73738

In [ ]:
encoder = tfds.deprecated.text.TokenTextEncoder(vocabulary_set)

In [ ]:
print(vocabulary_set)

{'Legends', 'heaviness', 'different', 'Samsing', 'eznsmart', 'powerheads', 'KINIVO', 'WMA', 'forcefully', 'Disk', 'unltrasuede', 'Polyester', 'flashplayer', 'workingand', 'Illumination', 'wondered', 'traver', 'Calibrating', 'CARFULLY', 'Wiley', 'reveived', 'icame', 'emotive', 'sport', '17W', 'protecion', 'casseste', 'floop', 'occasional', 'Feature', 'BR2', 'tambien', 'perflectly', 'B004VBIEZW', 'Lyrae', 'dials', 'SHIPPED', 'eachother', 'Classical', 'individualized', 'Launcher', 'afriad', 'nvidia', 'squawks', '500gb', 'prob', 'c2', '800mb', 'remoto', 'ofertas', 'ium', 'overboard', 'Cushion', 'piece', 'demure', 'PREGNANT', 'protruding', '60R', 'mimics', 'pipes', 'dignified', 'circuit', 'sd', 'Different', 'Sables', 'rejection', 'DISCMANS', '1296p', 'TrueVue', 'Batteries', 'mo26GFT6O7NETGE', 'competely', 'amp4', 'PHENOMENAL', 'Ruckus', 'usefull', 'ages', 'recitation', 'Song1', 'recomdnd', 'talkin', 'Gaussian', 'NILL', 'WOORKS', 'w204', 'Songbirds', 'chewed', '9885', 'environments', '105A',

In [ ]:
for reviews in train_datasets.take(5):
  review_text = reviews['data']
  print(review_text.get('review_body').numpy())
  encoded_example = encoder.encode(review_text.get('review_body').numpy())
  print(encoded_example)

b'I had this product before , but it mistakenly fell and cracked into pieces right before my eyes.  If you have good quality batteries you are good for a long period of time.  The replacement I purchased after my previous item fell into pieces was not in good shape as compared to my previous item, but the shipping came right on time. thanks.'
[46983, 1078, 23895, 8081, 56415, 33907, 13075, 42443, 16627, 62697, 6544, 41088, 54432, 7755, 56415, 64393, 11438, 36464, 34910, 10373, 59190, 26178, 10839, 34910, 16218, 59190, 61180, 48366, 11490, 43753, 48185, 68628, 32317, 28179, 46983, 41363, 37280, 64393, 11181, 59978, 16627, 41088, 54432, 53169, 9332, 36390, 59190, 72813, 20221, 72213, 56315, 64393, 11181, 59978, 33907, 48780, 12200, 29784, 7755, 38682, 68628, 25771]
b'It works great. Little loose in latch but works great for dog owners.'
[32295, 44418, 1494, 4488, 1225, 36390, 1634, 33907, 44418, 1494, 61180, 10540, 10314]
b'Fit perfect, and rather than throw your old GPS away, fix it ins

In [ ]:
for index in encoded_example:
  print('{} ----> {}'.format(index, encoder.decode([index])))

32295 ----> It
53169 ----> was
22384 ----> just
62310 ----> what
46983 ----> I
20506 ----> needed
62581 ----> wanted
62697 ----> and
34317 ----> more
46983 ----> I
12041 ----> could
9332 ----> not
67362 ----> bet
52156 ----> happier
46983 ----> I
38849 ----> would
70301 ----> highly
47816 ----> recommend
23895 ----> this
8081 ----> product


In [ ]:
def encode(text_tensor, label_tensor): #label is sentiment
  encoded_text = encoder.encode(text_tensor.numpy())
  label = tf.where(label_tensor > 3, 1,0)
  return encoded_text, label

In [ ]:
def encoded_map_fn(tensor):
  text = tensor['data'].get('review_body')
  label = tensor['data'].get('star_rating')

  encoded_text, label = tf.py_function(encode,
                                       inp = [text, label],
                                       Tout=(tf.int64, tf.int32))
  encoded_text.set_shape([None])
  label.set_shape([])

  return encoded_text, label

In [ ]:
ar_encoded_data = train_datasets.map(encoded_map_fn)

In [ ]:
for f0,f1 in ar_encoded_data.take(2):
  print(f0)
  print(f1)

tf.Tensor(
[46983  1078 23895  8081 56415 33907 13075 42443 16627 62697  6544 41088
 54432  7755 56415 64393 11438 36464 34910 10373 59190 26178 10839 34910
 16218 59190 61180 48366 11490 43753 48185 68628 32317 28179 46983 41363
 37280 64393 11181 59978 16627 41088 54432 53169  9332 36390 59190 72813
 20221 72213 56315 64393 11181 59978 33907 48780 12200 29784  7755 38682
 68628 25771], shape=(62,), dtype=int64)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(
[32295 44418  1494  4488  1225 36390  1634 33907 44418  1494 61180 10540
 10314], shape=(13,), dtype=int64)
tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
TAKE_SIZE = 10000

train_data = ar_encoded_data.skip(TAKE_SIZE).shuffle(BUFFER_SIZE)
train_data = train_data.padded_batch(BATCH_SIZE)

test_data = ar_encoded_data.take(TAKE_SIZE)
test_data = test_data.padded_batch(BATCH_SIZE)

In [ ]:
vocab_size += 1

In [ ]:
sample_text, sample_labels = next(iter(test_data)) #it will take 128 data at a time

sample_text[0], sample_labels[0]

(<tf.Tensor: shape=(378,), dtype=int64, numpy=
 array([46983,  1078, 23895,  8081, 56415, 33907, 13075, 42443, 16627,
        62697,  6544, 41088, 54432,  7755, 56415, 64393, 11438, 36464,
        34910, 10373, 59190, 26178, 10839, 34910, 16218, 59190, 61180,
        48366, 11490, 43753, 48185, 68628, 32317, 28179, 46983, 41363,
        37280, 64393, 11181, 59978, 16627, 41088, 54432, 53169,  9332,
        36390, 59190, 72813, 20221, 72213, 56315, 64393, 11181, 59978,
        33907, 48780, 12200, 29784,  7755, 38682, 68628, 25771,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,  

In [ ]:
model = tf.keras.Sequential() 
model.add(tf.keras.layers.Embedding(vocab_size, 128)) #creating an embedding layer
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(128, return_sequences=True)))
model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)))

# adding 2 dense layers of 64
for units in [64,64]:
  model.add(tf.keras.layers.Dense(units, activation="relu"))

# final layer
model.add(tf.keras.layers.Dense(1))

In [ ]:
!rm -r /tmp/logs/

rm: cannot remove '/tmp/logs/': No such file or directory


In [ ]:
logdir = os.path.join("/tmp/logs", datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)
checkpointer = tf.keras.callbacks.ModelCheckpoint(filepath="/tmp/sentiment_analysis.hdf5", verbose=1, save_best_only=True)

model.compile(optimizer="adam", loss=tf.keras.losses.BinaryCrossentropy(from_logits=True), metrics=["accuracy"])

In [ ]:
history = model.fit(train_data, epochs=1, validation_data=test_data, callbacks=[tensorboard_callback, checkpointer])

742/742 [==============================] - 6370s 9s/step - loss: 0.3009 - accuracy: 0.8719 - val_loss: 0.2838 - val_accuracy: 0.8723

Epoch 00001: val_loss improved from inf to 0.28382, saving model to /tmp/sentiment_analysis.hdf5


In [ ]:
model.save('/tmp/final_sentiment_analysis.hdf5')

In [ ]:
!ls -alrt /tmp/*.hdf5

-rw-r--r-- 1 root root 118636088 Jan 19 08:28 /tmp/sentiment_analysis.hdf5
-rw-r--r-- 1 root root 118636088 Jan 19 08:30 /tmp/final_sentiment_analysis.hdf5


In [ ]:
eval_loss, eval_acc = model.evaluate(test_data)

print('\nEval loss: {:.3f}, eval accuracy: {:.3f}'.format(eval_loss,eval_acc))

79/79 [==============================] - 184s 2s/step - loss: 0.2838 - accuracy: 0.8723

Eval loss: 0.284, eval accuracy: 0.872


In [ ]:
for f0,f1 in test_data.take(1):
  print(f1) #f1 is label f review
  print(model.predict(f0)) #f0 is actual review
  

tf.Tensor(
[1 1 1 0 1 0 0 1 1 0 1 1 0 0 1 1 1 0 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0 0 1 1 1
 1 1 0 0 1 1 1 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1
 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 0 1 1
 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0 0], shape=(128,), dtype=int32)
[[-2.9776566 ]
 [ 3.558467  ]
 [ 4.6495976 ]
 [-1.5924336 ]
 [ 3.581326  ]
 [-4.337909  ]
 [-2.64129   ]
 [ 4.1688375 ]
 [ 2.678685  ]
 [-3.7501397 ]
 [ 1.163845  ]
 [ 2.1736872 ]
 [-3.067455  ]
 [-2.352968  ]
 [ 1.1725593 ]
 [ 4.5139422 ]
 [ 4.108346  ]
 [-0.75922793]
 [ 2.8966558 ]
 [-0.6452343 ]
 [ 2.1914895 ]
 [ 4.0677023 ]
 [-2.6213417 ]
 [-2.0985193 ]
 [-4.302994  ]
 [ 3.9051836 ]
 [ 2.1729486 ]
 [ 2.3997436 ]
 [ 4.1676283 ]
 [ 3.5017123 ]
 [ 2.8780572 ]
 [ 5.56237   ]
 [-0.6045771 ]
 [-0.822845  ]
 [ 3.891731  ]
 [ 2.9237306 ]
 [ 2.9009604 ]
 [ 4.0595994 ]
 [ 4.358889  ]
 [-1.9252878 ]
 [-3.8433018 ]
 [ 4.229934  ]
 [ 2.98198   ]
 [ 3.7631605 ]
 [-2.9985096 ]
 [-4.1518755 ]
 [ 4.95005

In [ ]:
model.layers

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 128)         9438720   
_________________________________________________________________
bidirectional (Bidirectional (None, None, 256)         263168    
_________________________________________________________________
bidirectional_1 (Bidirection (None, 128)               164352    
_________________________________________________________________
dense (Dense)                (None, 64)                8256      
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 65        
Total params: 9,878,721
Trainable params: 9,878,721
Non-trainable params: 0
______________________________________________

In [ ]:
tf.keras.backend.clear_session()
sa_load = tf.keras.models.load_model("/tmp/sentiment_analysis.hdf5", compile=False)

In [ ]:
def pad_to_size(vec, size):
  zeros = [0]*(size - len(vec))
  vec.extend(zeros)
  return vec



In [ ]:
def predict_fn(pred_text):
  encoded_pred_text = encoder.encode(pred_text)
  # print(encoded_pred_text)
  encoded_pred_text = pad_to_size(encoded_pred_text, 32)
  # print(encoded_pred_text)
  encoded_pred_text = tf.cast(encoded_pred_text, tf.float32)
  predictions = sa_load.predict(tf.expand_dims(encoded_pred_text, 0))

  return (predictions[0][0])


In [ ]:
def get_sentiment(value):
  if (value > 0.0):
    return 'Positive'
  else:
    return 'Negative'

In [ ]:
pred_text = ('Color and dial does not look as advertised. Shipping was not any better as well')
predictions = predict_fn(pred_text)
sentiments = get_sentiment(predictions)
print(predictions)
print(sentiments)

-1.3886006
Negative


In [ ]:
pred_text = ('Amazing product. Fast Delivery. Nice Packing!')
predictions = predict_fn(pred_text)
sentiments = get_sentiment(predictions)
print(predictions)
print(sentiments)

5.7994075
Positive


In [ ]:
pred_text = ('This watch is pretty bad. Color and dial looks pathetic.')
predictions = predict_fn(pred_text)
sentiments = get_sentiment(predictions)
print(predictions)
print(sentiments)

-1.4252348
Negative


In [ ]:
pred_text = ('this product is worst and overall pathetic service')
predictions = predict_fn(pred_text)
sentiments = get_sentiment(predictions)
print(predictions)
print(sentiments)

-3.588606
Negative
